"""
Convert STL mesh to BDF format for TACS analysis.
"""

import os
import sys
import numpy as np


def read_stl_ascii(stl_file):
    """Read ASCII STL file."""
    vertices = []
    triangles = []

    with open(stl_file, 'r') as f:
        current_tri = []
        for line in f:
            line = line.strip()
            if line.startswith('vertex'):
                parts = line.split()
                vertex = [float(parts[1]), float(parts[2]), float(parts[3])]
                vertices.append(vertex)
                current_tri.append(len(vertices) - 1)

            elif line.startswith('endfacet'):
                if len(current_tri) == 3:
                    triangles.append(current_tri)
                current_tri = []

    return np.array(vertices), np.array(triangles)


def read_stl_binary(stl_file):
    """Read binary STL file."""
    with open(stl_file, 'rb') as f:
        # Read header (80 bytes)
        header = f.read(80)

        # Read number of triangles (4 bytes, unsigned int)
        num_triangles = np.frombuffer(f.read(4), dtype=np.uint32)[0]
        print(f"  Binary STL with {num_triangles} triangles")

        vertices = []
        triangles = []

        for i in range(num_triangles):
            # Read normal (12 bytes = 3 floats)
            normal = np.frombuffer(f.read(12), dtype=np.float32)

            # Read 3 vertices (36 bytes = 9 floats)
            v1 = np.frombuffer(f.read(12), dtype=np.float32)
            v2 = np.frombuffer(f.read(12), dtype=np.float32)
            v3 = np.frombuffer(f.read(12), dtype=np.float32)

            # Read attribute byte count (2 bytes)
            attr = np.frombuffer(f.read(2), dtype=np.uint16)

            # Add vertices
            idx1 = len(vertices)
            vertices.append(v1.tolist())
            vertices.append(v2.tolist())
            vertices.append(v3.tolist())

            triangles.append([idx1, idx1 + 1, idx1 + 2])

    return np.array(vertices), np.array(triangles)


def read_stl(stl_file):
    """Read STL file (auto-detect ASCII or binary)."""
    with open(stl_file, 'rb') as f:
        header = f.read(80)

    # Check if ASCII (starts with 'solid')
    try:
        header_str = header.decode('ascii').strip()
        if header_str.startswith('solid'):
            # Could be ASCII, but check further
            with open(stl_file, 'r') as f:
                first_lines = f.read(500)
                if 'facet normal' in first_lines:
                    print("  Detected ASCII STL format")
                    return read_stl_ascii(stl_file)
    except:
        pass

    print("  Detected binary STL format")
    return read_stl_binary(stl_file)


def merge_vertices(vertices, triangles, tolerance=1e-6):
    """Merge duplicate vertices within tolerance."""
    print(f"  Original: {len(vertices)} vertices, {len(triangles)} triangles")

    # Round vertices to merge duplicates
    scale = 1.0 / tolerance
    rounded = np.round(vertices * scale).astype(np.int64)

    # Create unique vertex map
    unique_dict = {}
    vertex_map = np.zeros(len(vertices), dtype=np.int32)
    unique_vertices = []

    for i, key in enumerate(map(tuple, rounded)):
        if key not in unique_dict:
            unique_dict[key] = len(unique_vertices)
            unique_vertices.append(vertices[i])
        vertex_map[i] = unique_dict[key]

    # Remap triangles
    new_triangles = vertex_map[triangles]

    print(f"  Merged: {len(unique_vertices)} vertices, {len(new_triangles)} triangles")

    return np.array(unique_vertices), new_triangles


def write_bdf(bdf_file, vertices, triangles, units='mm'):
    """
    Write BDF file from vertices and triangles.

    Parameters
    ----------
    bdf_file : str
        Output BDF file path
    vertices : ndarray
        Nx3 array of vertex coordinates
    triangles : ndarray
        Mx3 array of triangle vertex indices
    units : str
        Input units ('mm' or 'm')
    """
    # Convert mm to m if needed
    if units == 'mm':
        vertices = vertices / 1000.0
        print(f"  Converted from mm to m")

    with open(bdf_file, 'w') as f:
        f.write("$ pyNastran : punch=True\n")
        f.write("$ Nanuqx Flying Wing - Converted from STL\n")
        f.write("$ Generated by convert_stl_to_bdf.py\n")
        f.write("$\n")

        # Write nodes
        f.write("$ GRID POINTS\n")
        for i, (x, y, z) in enumerate(vertices):
            node_id = i + 1
            f.write(f"GRID,{node_id},,{x:.6e},{y:.6e},{z:.6e}\n")

        f.write("$\n")
        f.write("$ MATERIAL (Aluminum 7075-T6)\n")
        E = 71.7e9    # Young's modulus (Pa)
        nu = 0.33     # Poisson's ratio
        rho = 2810.0  # Density (kg/m^3) - use float
        # Use proper Nastran format with all fields as floats
        f.write(f"MAT1,1,{E:.4e},,{nu:.2f},{rho:.1f}\n")

        f.write("$\n")
        f.write("$ SHELL PROPERTY\n")
        thickness = 0.002  # 2mm shell thickness
        f.write(f"PSHELL,1,1,{thickness:.4f},1,,1\n")

        f.write("$\n")
        f.write("$ ELEMENTS\n")
        for i, (n1, n2, n3) in enumerate(triangles):
            elem_id = i + 1
            # BDF uses 1-based indexing
            f.write(f"CTRIA3,{elem_id},1,{n1+1},{n2+1},{n3+1}\n")

        # Add minimal constraints for solver stability
        # Find node closest to geometric center
        center = vertices.mean(axis=0)
        distances = np.linalg.norm(vertices - center, axis=1)
        ref_node_idx = np.argmin(distances)
        ref_node_id = ref_node_idx + 1

        # Find node farthest from center in X
        x_distances = np.abs(vertices[:, 0] - center[0])
        far_node_idx = np.argmax(x_distances)
        far_node_id = far_node_idx + 1

        # Find another node far in Y
        y_distances = np.abs(vertices[:, 1] - center[1])
        far_y_node_idx = np.argmax(y_distances)
        far_y_node_id = far_y_node_idx + 1

        f.write("$\n")
        f.write("$ MINIMAL CONSTRAINTS (for solver stability with inertial relief)\n")
        # Constrain all 6 DOFs at reference node
        f.write(f"SPC1,1,123456,{ref_node_id}\n")
        # Constrain Y, Z at far X node
        f.write(f"SPC1,1,23,{far_node_id}\n")
        # Constrain Z at far Y node
        f.write(f"SPC1,1,3,{far_y_node_id}\n")

        print(f"  Written {len(vertices)} nodes and {len(triangles)} elements")
        print(f"  Reference constraint node: {ref_node_id}")


def convert_stl_to_bdf(stl_file, bdf_file, units='mm', merge_tol=1e-6):
    """
    Convert STL file to BDF format.

    Parameters
    ----------
    stl_file : str
        Input STL file path
    bdf_file : str
        Output BDF file path
    units : str
        Units of STL file ('mm' or 'm')
    merge_tol : float
        Tolerance for merging duplicate vertices
    """
    print(f"\nReading STL: {stl_file}")
    vertices, triangles = read_stl(stl_file)

    print(f"\nMerging duplicate vertices...")
    vertices, triangles = merge_vertices(vertices, triangles, merge_tol)

    print(f"\nWriting BDF: {bdf_file}")
    write_bdf(bdf_file, vertices, triangles, units)

    # Print bounds
    x_min, x_max = vertices[:, 0].min(), vertices[:, 0].max()
    y_min, y_max = vertices[:, 1].min(), vertices[:, 1].max()
    z_min, z_max = vertices[:, 2].min(), vertices[:, 2].max()

    # Convert to meters for display if input was mm
    if units == 'mm':
        scale = 1000.0  # Display in mm
        unit_str = 'mm'
    else:
        scale = 1.0
        unit_str = 'm'

    print(f"\nMesh bounding box:")
    print(f"  X: {x_min*scale:.2f} to {x_max*scale:.2f} {unit_str}")
    print(f"  Y: {y_min*scale:.2f} to {y_max*scale:.2f} {unit_str}")
    print(f"  Z: {z_min*scale:.2f} to {z_max*scale:.2f} {unit_str}")

    return True


if __name__ == "__main__":
    # Input STL file from nTop
    stl_file = "/mnt/c/Users/bradrothenberg/OneDrive - nTop/OUT/parts/Group3_Test/OUT/Structure_Test1.stl"

    # Output directory
    output_dir = os.path.dirname(os.path.abspath(__file__))
    bdf_file = os.path.join(output_dir, "nanuqx_aircraft.bdf")

    print("=" * 60)
    print("CONVERTING NANUQX STL TO BDF")
    print("=" * 60)

    if not os.path.exists(stl_file):
        print(f"Error: STL file not found: {stl_file}")
        sys.exit(1)

    # Convert with mm units (typical for CAD exports)
    success = convert_stl_to_bdf(stl_file, bdf_file, units='mm', merge_tol=0.001)

    if success:
        print("\n" + "=" * 60)
        print("CONVERSION COMPLETE")
        print("=" * 60)
        print(f"\nOutput BDF: {bdf_file}")
    else:
        print("\nConversion failed!")
        sys.exit(1)
